title: My Blog
description: Welcome to my personal blog
theme: minima

minima:
  social_links:
    - { platform: github,   user_url: "https://github.com/Tantalor93" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/ond%C5%99ej-benkovsk%C3%BD-5b0842ba" }