title: My Blog

plugins:
  - jekyll-remote-theme
  - jekyll-feed

remote_theme: jekyll/minima@6b9b78d

minima:
  skin: auto
  social_links:
    - { platform: github,   user_url: "https://github.com/Tantalor93" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/ond%C5%99ej-benkovsk%C3%BD-5b0842ba" }