title: My Blog
description: Welcome to my personal blog
theme: minima

github_username: https://github.com/Tantalor93
linkedin_username: https://www.linkedin.com/in/ond%C5%99ej-benkovsk%C3%BD-5b0842ba